.TH "src Directory Reference" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcontour\&.cpp\fP"
.br
.RI "Computation of the contour for a set of iso-rectangles using divide-and-conquer\&. "
.ti -1c
.RI "file \fBcontour_visual\&.py\fP"
.br
.ti -1c
.RI "file \fBmeasure\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmeasure_visual\&.py\fP"
.br
.in -1c
