.TH "contour_visual" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
contour_visual
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfig\fP"
.br
.ti -1c
.RI "\fBax\fP"
.br
.ti -1c
.RI "\fBxmin\fP = min(\fBx1\fP, \fBx2\fP, xmin)"
.br
.ti -1c
.RI "\fBxmax\fP = max(\fBx1\fP, \fBx2\fP, xmax)"
.br
.ti -1c
.RI "\fBymin\fP = min(\fBy1\fP, \fBy2\fP, ymin)"
.br
.ti -1c
.RI "\fBymax\fP = max(\fBy1\fP, \fBy2\fP, ymax)"
.br
.ti -1c
.RI "\fBlines\fP = f\&.readlines()[1:]"
.br
.ti -1c
.RI "\fBx1\fP"
.br
.ti -1c
.RI "\fBx2\fP"
.br
.ti -1c
.RI "\fBy1\fP"
.br
.ti -1c
.RI "\fBy2\fP"
.br
.ti -1c
.RI "\fBrect\fP = patches\&.Rectangle((\fBx1\fP, \fBy1\fP), \fBx2\fP\-\fBx1\fP, \fBy2\fP\-\fBy1\fP, \fBlinewidth\fP=1, edgecolor='r', facecolor=(0,0,0,0\&.2))"
.br
.ti -1c
.RI "\fBfxmin\fP"
.br
.ti -1c
.RI "\fBfxmax\fP"
.br
.ti -1c
.RI "\fBfymin\fP"
.br
.ti -1c
.RI "\fBfymax\fP"
.br
.ti -1c
.RI "\fBelems\fP = line\&.split()"
.br
.ti -1c
.RI "\fBm\fP = float(\fBelems\fP[4])"
.br
.ti -1c
.RI "\fBcolor\fP"
.br
.ti -1c
.RI "\fBlinewidth\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "contour_visual\&.ax"

.SS "contour_visual\&.color"

.SS "contour_visual\&.elems = line\&.split()"

.SS "contour_visual\&.fig"

.SS "contour_visual\&.fxmax"

.SS "contour_visual\&.fxmin"

.SS "contour_visual\&.fymax"

.SS "contour_visual\&.fymin"

.SS "contour_visual\&.lines = f\&.readlines()[1:]"

.SS "contour_visual\&.linewidth"

.SS "contour_visual\&.m = float(\fBelems\fP[4])"

.SS "contour_visual\&.rect = patches\&.Rectangle((\fBx1\fP, \fBy1\fP), \fBx2\fP\-\fBx1\fP, \fBy2\fP\-\fBy1\fP, \fBlinewidth\fP=1, edgecolor='r', facecolor=(0,0,0,0\&.2))"

.SS "contour_visual\&.x1"

.SS "contour_visual\&.x2"

.SS "contour_visual\&.xmax = max(\fBx1\fP, \fBx2\fP, xmax)"

.SS "contour_visual\&.xmin = min(\fBx1\fP, \fBx2\fP, xmin)"

.SS "contour_visual\&.y1"

.SS "contour_visual\&.y2"

.SS "contour_visual\&.ymax = max(\fBy1\fP, \fBy2\fP, ymax)"

.SS "contour_visual\&.ymin = min(\fBy1\fP, \fBy2\fP, ymin)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
