.TH "src/contour_visual.py" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contour_visual.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcontour_visual\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBcontour_visual\&.fig\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.ax\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.xmin\fP = min(x1, x2, xmin)"
.br
.ti -1c
.RI "\fBcontour_visual\&.xmax\fP = max(x1, x2, xmax)"
.br
.ti -1c
.RI "\fBcontour_visual\&.ymin\fP = min(y1, y2, ymin)"
.br
.ti -1c
.RI "\fBcontour_visual\&.ymax\fP = max(y1, y2, ymax)"
.br
.ti -1c
.RI "\fBcontour_visual\&.lines\fP = f\&.readlines()[1:]"
.br
.ti -1c
.RI "\fBcontour_visual\&.x1\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.x2\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.y1\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.y2\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.rect\fP = patches\&.Rectangle((x1, y1), x2\-x1, y2\-y1, linewidth=1, edgecolor='r', facecolor=(0,0,0,0\&.2))"
.br
.ti -1c
.RI "\fBcontour_visual\&.fxmin\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.fxmax\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.fymin\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.fymax\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.elems\fP = line\&.split()"
.br
.ti -1c
.RI "\fBcontour_visual\&.m\fP = float(elems[4])"
.br
.ti -1c
.RI "\fBcontour_visual\&.color\fP"
.br
.ti -1c
.RI "\fBcontour_visual\&.linewidth\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
