.TH "ctree" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ctree \- A class to represent a binary tree\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBctree\fP ()"
.br
.RI "Default constructor to create a ctree object\&. "
.ti -1c
.RI "\fBctree\fP (T \fBx\fP, string \fBside\fP, \fBctree\fP *\fBlson\fP, \fBctree\fP *\fBrson\fP)"
.br
.RI "Constructor to create a ctree object with given initialisation values\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.RI "x-coordinate of the vertical edge "
.ti -1c
.RI "string \fBside\fP"
.br
.RI "type of side "
.ti -1c
.RI "\fBctree\fP * \fBlson\fP"
.br
.RI "pointer to left child of current nude of tree "
.ti -1c
.RI "\fBctree\fP * \fBrson\fP"
.br
.RI "pointer to right child of current node of tree "
.in -1c
.SH "Detailed Description"
.PP 
A class to represent a binary tree\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ctree::ctree ()\fC [inline]\fP"

.PP
Default constructor to create a ctree object\&. 
.PP
\fBReturns\fP
.RS 4
Empty object of class ctree 
.RE
.PP

.SS "ctree::ctree (T x, string side, \fBctree\fP * lson, \fBctree\fP * rson)\fC [inline]\fP"

.PP
Constructor to create a ctree object with given initialisation values\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP Value for x-coordinate of an edge 
.br
\fIside\fP Value for type of side 
.br
\fIlson\fP Value for left Pointer 
.br
\fIrson\fP Value for left Pointer 
.RE
.PP
\fBReturns\fP
.RS 4
Object of class ctree initialised with given values 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
