.TH "src/measure.cpp" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/measure.cpp \- Computation of the measure for a set of iso rectangles using divide-and-conquer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <bits/stdc++\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "A simple class to represent a point in a two dimensional space\&. "
.ti -1c
.RI "class \fBInterval\fP"
.br
.RI "A class to represent an interval between two lines in the 2D plane\&. "
.ti -1c
.RI "class \fBLineSegment\fP"
.br
.RI "A class to represent a Line Segment between the given interval of two points with coord as the offset from the axes\&. "
.ti -1c
.RI "class \fBRectangle\fP"
.br
.RI "A class to represent a rectangle in a two dimensional space\&. "
.ti -1c
.RI "class \fBEdge\fP"
.br
.RI "A class to represent an edge in two dimensional space\&. "
.ti -1c
.RI "class \fBStripe\fP"
.br
.RI "A class to represent a horizontal stripe in two dimensions\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBtplate\fP   template <typename T = long double>"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class T > set< T > \fBoperator\-\fP (set< T > a, set< T > b)"
.br
.RI "Defines the minus operator for computing set difference of set A and set B\&. "
.ti -1c
.RI "template<class T > set< T > \fBoperator+\fP (set< T > a, set< T > b)"
.br
.RI "Defines the plus operator for computing union of set A and set B\&. "
.ti -1c
.RI "template<class T > set< T > \fBoperator^\fP (set< T > a, set< T > b)"
.br
.RI "Defines the intersection operator for computing set intersection of two sets\&. "
.ti -1c
.RI "tplate set< \fBInterval\fP< T > > \fBpartition\fP (set< T > Y)"
.br
.RI "Finds intervals created by a set of coordinates\&. "
.ti -1c
.RI "tplate set< \fBStripe\fP< T > > \fBCopy\fP (set< \fBStripe\fP< T >> S, set< T > P, \fBInterval\fP< T > x_int)"
.br
.RI "Copies a set of stripes into the stripes created by partitions\&. "
.ti -1c
.RI "tplate void \fBBlacken\fP (set< \fBStripe\fP< T >> &S, set< \fBInterval\fP< T >> J)"
.br
.RI "Removes the edges that are covered by other rectangles for a particular stripe\&. "
.ti -1c
.RI "tplate set< \fBStripe\fP< T > > \fBConcat\fP (set< \fBStripe\fP< T >> S1, set< \fBStripe\fP< T >> S2, set< T > P, \fBInterval\fP< T > x_int)"
.br
.RI "Combine the results from two sets of stripes\&. "
.ti -1c
.RI "tplate set< \fBStripe\fP< T > > \fBSTRIPES\fP (vector< \fBEdge\fP< T >> &V, \fBInterval\fP< T > &x_ext, set< \fBInterval\fP< T >> &L, set< \fBInterval\fP< T >> &R, set< T > &P)"
.br
.RI "Creates the stripes required for finding the contour\&. "
.ti -1c
.RI "tplate set< \fBStripe\fP< T > > \fBRECTANGLE_DAC\fP (set< \fBRectangle\fP< T >> RECT)"
.br
.RI "A helper function that converts the \fBRectangle\fP into edges and calls the STRIPES function on those intervals\&. "
.ti -1c
.RI "int \fBmain\fP (int argc, char const *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "tplate const T \fBinf\fP = numeric_limits<T>::infinity()"
.br
.RI "Constant to represent infinity\&. "
.in -1c
.SH "Detailed Description"
.PP 
Computation of the measure for a set of iso rectangles using divide-and-conquer\&. 


.SH "Function Documentation"
.PP 
.SS "tplate void Blacken (set< \fBStripe\fP< T >> & S, set< \fBInterval\fP< T >> J)"

.PP
Removes the edges that are covered by other rectangles for a particular stripe\&. 
.PP
\fBParameters\fP
.RS 4
\fIS\fP Set of stripes 
.br
\fIJ\fP Set of Intervals 
.RE
.PP

.SS "tplate set<\fBStripe\fP<T> > Concat (set< \fBStripe\fP< T >> S1, set< \fBStripe\fP< T >> S2, set< T > P, \fBInterval\fP< T > x_int)"

.PP
Combine the results from two sets of stripes\&. 
.PP
\fBParameters\fP
.RS 4
\fIS1\fP First set of stripes 
.br
\fIS2\fP Second set of stripes 
.br
\fIP\fP Set of coordinates 
.br
\fIx_int\fP \fBInterval\fP on x-axis for both sets of stripes 
.RE
.PP
\fBReturns\fP
.RS 4
A set of stripes after concatenation 
.RE
.PP

.SS "tplate set<\fBStripe\fP<T> > Copy (set< \fBStripe\fP< T >> S, set< T > P, \fBInterval\fP< T > x_int)"

.PP
Copies a set of stripes into the stripes created by partitions\&. 
.PP
\fBParameters\fP
.RS 4
\fIS\fP Set of stripes 
.br
\fIP\fP Set of coordinates 
.br
\fIx_int\fP \fBInterval\fP of stripes on x-axis 
.RE
.PP
\fBReturns\fP
.RS 4
A set of stripes 
.RE
.PP

.SS "template<class T > set<T> operator+ (set< T > a, set< T > b)"

.PP
Defines the plus operator for computing union of set A and set B\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP set a 
.br
\fIb\fP set b 
.RE
.PP
\fBReturns\fP
.RS 4
a set with the union of set a and set b 
.RE
.PP

.SS "template<class T > set<T> operator\- (set< T > a, set< T > b)"

.PP
Defines the minus operator for computing set difference of set A and set B\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP the set from which to elements are to be removed 
.br
\fIb\fP the set of items to be removed 
.RE
.PP
\fBReturns\fP
.RS 4
a set with items of set b removed 
.RE
.PP

.SS "template<class T > set<T> operator^ (set< T > a, set< T > b)"

.PP
Defines the intersection operator for computing set intersection of two sets\&. 
.PP
\fBParameters\fP
.RS 4
\fIa\fP set a 
.br
\fIb\fP set b 
.RE
.PP
\fBReturns\fP
.RS 4
intersection of set a and set b 
.RE
.PP

.SS "tplate set<\fBInterval\fP<T> > partition (set< T > Y)"

.PP
Finds intervals created by a set of coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIY\fP set of y-coordinates 
.RE
.PP
\fBReturns\fP
.RS 4
A set of intervals 
.RE
.PP

.SS "tplate set<\fBStripe\fP<T> > RECTANGLE_DAC (set< \fBRectangle\fP< T >> RECT)"

.PP
A helper function that converts the \fBRectangle\fP into edges and calls the STRIPES function on those intervals\&. 
.PP
\fBParameters\fP
.RS 4
\fIRECT\fP A set of Rectangles 
.RE
.PP
\fBReturns\fP
.RS 4
A set of stripes 
.RE
.PP

.SS "tplate set<\fBStripe\fP<T> > STRIPES (vector< \fBEdge\fP< T >> & V, \fBInterval\fP< T > & x_ext, set< \fBInterval\fP< T >> & L, set< \fBInterval\fP< T >> & R, set< T > & P)"

.PP
Creates the stripes required for finding the contour\&. 
.PP
\fBParameters\fP
.RS 4
\fIV\fP Set of edges 
.br
\fIx_ext\fP \fBInterval\fP on x-axis for set of stripes 
.br
\fIL\fP Intervals consisting of 'left' edges 
.br
\fIR\fP Intervals consisting of 'right' edges 
.br
\fIP\fP Set of coordinates 
.RE
.PP
\fBReturns\fP
.RS 4
A set of stripes 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
