.TH "Point" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point \- A simple class to represent a point in a two dimensional space\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPoint\fP (T \fBx\fP, T \fBy\fP)"
.br
.RI "This constructor is used to initialise the object with given x and y coordinates\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPoint\fP &other) const"
.br
.RI "Defines the less-than operator for set insertion and comparision\&. "
.ti -1c
.RI "\fBPoint\fP (T \fBx\fP, T \fBy\fP)"
.br
.RI "This constructor is used to initialise the object with given x and y coordinates\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBPoint\fP &other) const"
.br
.RI "Defines the less-than operator for set insertion and comparision\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "T \fBx\fP"
.br
.RI "x-coordinate of the point represented by the object "
.ti -1c
.RI "T \fBy\fP"
.br
.RI "y-coordinate of the point represented by the object "
.in -1c
.SH "Detailed Description"
.PP 
A simple class to represent a point in a two dimensional space\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Point::Point (T x, T y)\fC [inline]\fP"

.PP
This constructor is used to initialise the object with given x and y coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP x-coordinate 
.br
\fIy\fP y-coordinate 
.RE
.PP
\fBReturns\fP
.RS 4
The object initialised with the given coordinates 
.RE
.PP

.SS "Point::Point (T x, T y)\fC [inline]\fP"

.PP
This constructor is used to initialise the object with given x and y coordinates\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP x-coordinate 
.br
\fIy\fP y-coordinate 
.RE
.PP
\fBReturns\fP
.RS 4
The object initialised with the given coordinates 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Point::operator< (const \fBPoint\fP & other) const\fC [inline]\fP"

.PP
Defines the less-than operator for set insertion and comparision\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP object with which comparision needs to be done 
.RE
.PP
\fBReturns\fP
.RS 4
true if object less than other, else false 
.RE
.PP

.SS "bool Point::operator< (const \fBPoint\fP & other) const\fC [inline]\fP"

.PP
Defines the less-than operator for set insertion and comparision\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP object with which comparision needs to be done 
.RE
.PP
\fBReturns\fP
.RS 4
true if object less than other, else false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
