.TH "Stripe" 3 "Wed Mar 17 2021" "Our Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Stripe \- A class to represent a horizontal stripe in two dimensions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStripe\fP ()"
.br
.RI "Default constructor to create a \fBStripe\fP object\&. "
.ti -1c
.RI "\fBStripe\fP (\fBInterval\fP< T > \fBx_interval\fP, \fBInterval\fP< T > \fBy_interval\fP, \fBctree\fP< T > *\fBtree\fP)"
.br
.RI "Constructor to create a \fBStripe\fP object with given initialisation values\&. "
.ti -1c
.RI "bool \fBoperator<\fP (const \fBStripe\fP &other) const"
.br
.RI "Defines the less-than operator for set insertion and comparision\&. "
.ti -1c
.RI "\fBStripe\fP (\fBInterval\fP< T > x, \fBInterval\fP< T > y, T m)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBStripe\fP &other) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBInterval\fP< T > \fBx_interval\fP"
.br
.RI "\fBInterval\fP of the stripe on the x-axis\&. "
.ti -1c
.RI "\fBInterval\fP< T > \fBy_interval\fP"
.br
.RI "\fBInterval\fP of the stripe on the y-axis\&. "
.ti -1c
.RI "\fBctree\fP< T > * \fBtree\fP"
.br
.RI "Pointer to root of a binary tree\&. "
.ti -1c
.RI "T \fBx_measure\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to represent a horizontal stripe in two dimensions\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Stripe::Stripe ()\fC [inline]\fP"

.PP
Default constructor to create a \fBStripe\fP object\&. 
.PP
\fBReturns\fP
.RS 4
Empty object of class Strie 
.RE
.PP

.SS "Stripe::Stripe (\fBInterval\fP< T > x_interval, \fBInterval\fP< T > y_interval, \fBctree\fP< T > * tree)\fC [inline]\fP"

.PP
Constructor to create a \fBStripe\fP object with given initialisation values\&. 
.PP
\fBParameters\fP
.RS 4
\fIx_interval\fP Value for x_interval 
.br
\fIy_interval\fP Value for y_interval 
.br
\fItree\fP Value for root Pointer 
.RE
.PP
\fBReturns\fP
.RS 4
Object of class \fBStripe\fP initialised with given values 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool Stripe::operator< (const \fBStripe\fP & other) const\fC [inline]\fP"

.PP
Defines the less-than operator for set insertion and comparision\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP object with which comparision needs to be done 
.RE
.PP
\fBReturns\fP
.RS 4
true if object less than other, else false 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Our Project from the source code\&.
